default: &default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_tracker_development

test:
  <<: *default
  database: task_tracker_test

production:
  <<: *default
  database: task_tracker_production